name: Git repo mirroring for Pagure
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  silverblue:
    runs-on: ubuntu-latest
    steps:
      - run: git clone https://pagure.io/fedora-docs-l10n/fedora-silverblue.git
      - run: cd fedora-silverblue
      - run: git push https://${GITHUB_TOKEN}@github.com/bobby285271/fedora-docs-l10n-fedora-silverblue.git --force 'refs/heads/*:refs/heads/*'
      
      - run: git clone https://pagure.io/fedora-docs-l10n/fedora-install-guide.git
      - run: cd fedora-install-guide
      - run: git push https://${GITHUB_TOKEN}@github.com/bobby285271/fedora-docs-l10n-fedora-install-guide.git --force 'refs/heads/*:refs/heads/*'
