name: Git repo mirroring for Pagure
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
  
jobs:
  silverblue:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE }}
        with:
          source-repo: 'https://pagure.io/fedora-docs-l10n/fedora-silverblue.git'
          destination-repo: 'git@github.com:bobby285271/fedora-docs-l10n-fedora-silverblue.git'
   
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE }}
        with:
          source-repo: 'https://pagure.io/fedora-docs-l10n/fedora-install-guide.git'
          destination-repo: 'git@github.com:bobby285271/fedora-docs-l10n-fedora-install-guide.git'
          
